# Generated by Django 5.0.7 on 2024-07-23 16:54

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='jid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', editable=False, length=6, max_length=255, prefix='event-', unique=True),
        ),
    ]
