# Generated by Django 5.0.7 on 2024-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profileemployeur_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileemployeur',
            name='facebook_link',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profileemployeur',
            name='instagram_link',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profileemployeur',
            name='linkedin_link',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profileemployeur',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profileemployeur',
            name='twetter_link',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profileemployeur',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profileemployeur',
            name='youtube_link',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profileemployeur',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
